# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_auto_20170626_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyimage',
            old_name='product',
            new_name='emergency',
        ),
    ]
