# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0006_emergencyimage_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyimage',
            name='emergency',
        ),
        migrations.AddField(
            model_name='emergency',
            name='image',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
        migrations.DeleteModel(
            name='EmergencyImage',
        ),
    ]
