# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0008_auto_20170630_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='image',
        ),
        migrations.AddField(
            model_name='emergency',
            name='person_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='phone',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
